import type { Metadata } from "next";
import { Instrument_Sans, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { Header } from "./widgets";
import Provider from "./provider";
import ScrollProvider from "./context/ScrollContext";
import MenuModal from "./widgets/modal/MenuModal";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <ScrollProvider>
          <body
            className={`${instrumentSans.variable} ${instrumentSerif.variable} antialiased`}
          >
            <Header />
            {children}
            {/* <MenuModal /> */}
          </body>
        </ScrollProvider>
      </Provider>
    </html>
  );
}
